import { StyleSheet } from "react-native";

export const MAX_MOOD_LEVEL = 5;
export const BAR_HEIGHT_MULTIPLIER = 22;

export const styles = StyleSheet.create({
	container: { flex: 1, backgroundColor: "#fff" },
	center: { justifyContent: "center", alignItems: "center" },
	screen: {
		flex: 1,
		paddingHorizontal: 20,
		paddingBottom: 20,
		backgroundColor: "#f8f9fa",
	},
	header: {
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		paddingBottom: 15,
		borderBottomWidth: 1,
		borderBottomColor: "#e9ecef",
		marginBottom: 10,
	},
	header_form: {
		flexDirection: "row",
		alignItems: "center",
		paddingBottom: 15,
		borderBottomWidth: 1,
		borderBottomColor: "#e9ecef",
		marginBottom: 10,
	},
	headerLeft: { width: 60 },
	headerCenter: { flex: 1, alignItems: "center" },
	headerRight: { width: 60, alignItems: "flex-end" },
	headerTitle: { fontSize: 17, fontWeight: "600", color: "#343a40" },
	headerActionText: { fontSize: 24, color: "#007bff", fontWeight: "300" },
	headerActionTextBold: { fontSize: 16, color: "#007bff", fontWeight: "600" },
	homeContent: { flex: 1, justifyContent: "center" },
	footer: { paddingTop: 10 },
	label: {
		fontSize: 16,
		color: "#495057",
		marginBottom: 8,
		textAlign: "center",
	},
	formLabel: { fontSize: 16, color: "#495057", marginBottom: 8 },
	input: {
		backgroundColor: "white",
		borderWidth: 1,
		borderColor: "#ced4da",
		borderRadius: 8,
		padding: 12,
		fontSize: 16,
	},
	textarea: {
		backgroundColor: "white",
		borderWidth: 1,
		borderColor: "#ced4da",
		borderRadius: 8,
		padding: 12,
		fontSize: 16,
		textAlignVertical: "top",
		minHeight: 100,
	},
	button: {
		paddingVertical: 15,
		borderRadius: 8,
		alignItems: "center",
		marginBottom: 10,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 3,
	},
	blueButton: { backgroundColor: "#007bff" },
	grayButton: { backgroundColor: "#e9ecef" },
	buttonTextWhite: { color: "white", fontSize: 16, fontWeight: "bold" },
	buttonTextGray: { color: "#495057", fontSize: 16, fontWeight: "bold" },
	formContainer: { flex: 1 },
	inputGroup: { marginBottom: 20 },
	listContainer: { flex: 1 },
	logItem: {
		backgroundColor: "white",
		padding: 15,
		borderRadius: 8,
		marginBottom: 10,
		borderWidth: 1,
		borderColor: "#e9ecef",
	},
	logItemHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginBottom: 5,
	},
	logDate: { fontSize: 12, color: "#6c757d" },
	logThought: {
		fontSize: 16,
		fontWeight: "500",
		color: "#343a40",
		marginBottom: 8,
	},
	moodContainer: {
		flexDirection: "row",
		alignItems: "flex-start",
		marginTop: 8,
		borderTopWidth: 1,
		borderTopColor: "#f1f3f5",
		paddingTop: 8,
	},
	moodText: { fontSize: 14, color: "#495057", lineHeight: 22 },
	moodArrow: {
		marginHorizontal: 8,
		color: "#6c757d",
		fontSize: 18,
		fontWeight: "bold",
		alignSelf: "center",
	},
	redButton: { backgroundColor: "#dc3545", marginTop: 20 },
	moodsWrapper: { marginBottom: 10 },
	moodInputRow: {
		flexDirection: "row",
		alignItems: "center",
		marginBottom: 8,
		backgroundColor: "white",
		paddingVertical: 4,
		paddingHorizontal: 12,
		borderRadius: 8,
		borderWidth: 1,
		borderColor: "#e9ecef",
	},
	moodName: { flex: 1, fontSize: 16, color: "#343a40", fontWeight: "500" },
	levelSelector: { flexDirection: "row" },
	levelEmoji: { fontSize: 20, marginHorizontal: 3 },
	removeButton: { marginLeft: 10, padding: 5 },
	removeButtonText: { fontSize: 20, color: "#adb5bd" },
	tagContainer: { flexDirection: "row", flexWrap: "wrap" },
	tag: {
		backgroundColor: "#e9ecef",
		borderRadius: 15,
		paddingVertical: 8,
		paddingHorizontal: 12,
		marginRight: 8,
		marginBottom: 8,
	},
	tagText: { color: "#495057", fontSize: 14 },
	clearButton: { marginTop: 20, padding: 10, alignItems: "center" },
	clearButtonText: {
		fontSize: 12,
		color: "#6c757d",
		textDecorationLine: "underline",
	},
	emptyText: { textAlign: "center", color: "#6c757d", marginTop: 40 },
	tagSelected: { backgroundColor: "#007bff" },
	tagTextSelected: { color: "white" },
	chartContainer: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		marginTop: 10,
	},
	chartWrapper: {
		flexDirection: "row",
		alignItems: "flex-end",
		width: "100%",
		borderBottomWidth: 1,
		borderBottomColor: "#ced4da",
		paddingBottom: 5,
	},
	yAxisContainer: {
		height: MAX_MOOD_LEVEL * BAR_HEIGHT_MULTIPLIER,
		justifyContent: "space-between",
		paddingRight: 5,
		alignItems: "flex-end",
	},
	yAxisLabel: { fontSize: 12, color: "#6c757d" },
	barChart: {
		flexDirection: "row",
		alignItems: "flex-end",
		height: MAX_MOOD_LEVEL * BAR_HEIGHT_MULTIPLIER,
		paddingLeft: 10,
	},
	barGroup: { flex: 1, alignItems: "center", minWidth: 50 },
	barWrapper: {
		width: "80%",
		height: MAX_MOOD_LEVEL * BAR_HEIGHT_MULTIPLIER,
		alignItems: "center",
	},
	bar: { width: "60%", borderRadius: 3, position: "absolute", bottom: 0 },
	barBefore: { backgroundColor: "rgba(220, 53, 69, 0.6)" },
	barAfter: { backgroundColor: "rgba(40, 167, 69, 0.6)" },
	barLabel: { marginTop: 5, fontSize: 12, color: "#6c757d" },
	legendContainer: {
		flexDirection: "row",
		justifyContent: "center",
		marginTop: 15,
		padding: 10,
		backgroundColor: "#e9ecef",
		borderRadius: 8,
	},
	legendItem: {
		flexDirection: "row",
		alignItems: "center",
		marginHorizontal: 10,
	},
	legendColor: { width: 15, height: 15, marginRight: 5, borderRadius: 3 },
	favoriteButton: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "flex-end",
		marginTop: -10,
		marginBottom: 10,
	},
	favoriteIcon: { fontSize: 24, color: "#ced4da" },
	favoriteIconActive: { fontSize: 24, color: "#ffc107" },
	favoriteButtonText: { marginLeft: 5, color: "#6c757d", fontSize: 14 },
	logFavoriteButton: { padding: 5 },
	tabBar: {
		flexDirection: "row",
		backgroundColor: "white",
		borderTopWidth: 1,
		borderTopColor: "#e9ecef",
	},
	tabItem: { flex: 1, alignItems: "center", paddingVertical: 15 },
	tabText: { color: "#6c757d" },
	tabTextActive: { color: "#007bff", fontWeight: "bold" },
	kizukiCard: {
		backgroundColor: "white",
		padding: 20,
		borderRadius: 8,
		marginBottom: 15,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.1,
		shadowRadius: 2,
		elevation: 2,
	},
	kizukiText: {
		fontSize: 16,
		color: "#343a40",
		lineHeight: 24,
		marginBottom: 15,
	},
	kizukiDate: { fontSize: 12, color: "#adb5bd", textAlign: "right" },
});
